//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Codist.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Codist.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Parallel Watch.
        /// </summary>
        internal static string CMD_AddParallelWatch {
            get {
                return ResourceManager.GetString("CMD_AddParallelWatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Watch.
        /// </summary>
        internal static string CMD_AddWatch {
            get {
                return ResourceManager.GetString("CMD_AddWatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyze symbol....
        /// </summary>
        internal static string CMD_AnalyzeSymbol {
            get {
                return ResourceManager.GetString("CMD_AnalyzeSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capitalize.
        /// </summary>
        internal static string CMD_Capitalize {
            get {
                return ResourceManager.GetString("CMD_Capitalize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear filter.
        /// </summary>
        internal static string CMD_ClearFilter {
            get {
                return ResourceManager.GetString("CMD_ClearFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string CMD_Close {
            get {
                return ResourceManager.GetString("CMD_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment selection
        ///Right click: Comment line.
        /// </summary>
        internal static string CMD_CommentSelection {
            get {
                return ResourceManager.GetString("CMD_CommentSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Qualified Symbol Name.
        /// </summary>
        internal static string CMD_CopyQualifiedSymbolName {
            get {
                return ResourceManager.GetString("CMD_CopyQualifiedSymbolName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy selected text
        ///Right click: Copy line.
        /// </summary>
        internal static string CMD_CopySelectedText {
            get {
                return ResourceManager.GetString("CMD_CopySelectedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Symbol Name.
        /// </summary>
        internal static string CMD_CopySymbolName {
            get {
                return ResourceManager.GetString("CMD_CopySymbolName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut selected text
        ///Right click: Cut line.
        /// </summary>
        internal static string CMD_CutSelectedText {
            get {
                return ResourceManager.GetString("CMD_CutSelectedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debugger...
        ///Left click: Toggle breakpoint
        ///Right click: Debugger menu....
        /// </summary>
        internal static string CMD_Debugger {
            get {
                return ResourceManager.GetString("CMD_Debugger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete All Breakpoints.
        /// </summary>
        internal static string CMD_DeleteAllBreakpoints {
            get {
                return ResourceManager.GetString("CMD_DeleteAllBreakpoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected text
        ///Right click: Delete line
        ///Ctrl click: Delete and select next.
        /// </summary>
        internal static string CMD_DeleteSelectedText {
            get {
                return ResourceManager.GetString("CMD_DeleteSelectedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate selection
        ///Right click: Duplicate line.
        /// </summary>
        internal static string CMD_DuplicateSelection {
            get {
                return ResourceManager.GetString("CMD_DuplicateSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract interface.
        /// </summary>
        internal static string CMD_ExtractInterface {
            get {
                return ResourceManager.GetString("CMD_ExtractInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract Method.
        /// </summary>
        internal static string CMD_ExtractMethod {
            get {
                return ResourceManager.GetString("CMD_ExtractMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find....
        /// </summary>
        internal static string CMD_Find {
            get {
                return ResourceManager.GetString("CMD_Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find All References.
        /// </summary>
        internal static string CMD_FindAllReferences {
            get {
                return ResourceManager.GetString("CMD_FindAllReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Callers....
        /// </summary>
        internal static string CMD_FindCallers {
            get {
                return ResourceManager.GetString("CMD_FindCallers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Constructor Callers....
        /// </summary>
        internal static string CMD_FindConstructorCallers {
            get {
                return ResourceManager.GetString("CMD_FindConstructorCallers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Derived Classes....
        /// </summary>
        internal static string CMD_FindDerivedClasses {
            get {
                return ResourceManager.GetString("CMD_FindDerivedClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Extensions....
        /// </summary>
        internal static string CMD_FindExtensions {
            get {
                return ResourceManager.GetString("CMD_FindExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Extensions for &lt;TYPE&gt;....
        /// </summary>
        internal static string CMD_FindExtensionsFor {
            get {
                return ResourceManager.GetString("CMD_FindExtensionsFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Implementations....
        /// </summary>
        internal static string CMD_FindImplementations {
            get {
                return ResourceManager.GetString("CMD_FindImplementations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find in Files....
        /// </summary>
        internal static string CMD_FindInFiles {
            get {
                return ResourceManager.GetString("CMD_FindInFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Instance as Parameter....
        /// </summary>
        internal static string CMD_FindInstanceAsParameter {
            get {
                return ResourceManager.GetString("CMD_FindInstanceAsParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Instance Producer....
        /// </summary>
        internal static string CMD_FindInstanceProducer {
            get {
                return ResourceManager.GetString("CMD_FindInstanceProducer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Members....
        /// </summary>
        internal static string CMD_FindMembers {
            get {
                return ResourceManager.GetString("CMD_FindMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Members of &lt;TYPE&gt;....
        /// </summary>
        internal static string CMD_FindMembersOf {
            get {
                return ResourceManager.GetString("CMD_FindMembersOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Methods with Same Signature....
        /// </summary>
        internal static string CMD_FindMethodsSameSignature {
            get {
                return ResourceManager.GetString("CMD_FindMethodsSameSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Overrides....
        /// </summary>
        internal static string CMD_FindOverrides {
            get {
                return ResourceManager.GetString("CMD_FindOverrides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Referenced Symbols....
        /// </summary>
        internal static string CMD_FindReferencedSymbols {
            get {
                return ResourceManager.GetString("CMD_FindReferencedSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Referrers....
        /// </summary>
        internal static string CMD_FindReferrers {
            get {
                return ResourceManager.GetString("CMD_FindReferrers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find next selected text
        ///Ctrl click: Find match case
        ///Right click: Find and replace....
        /// </summary>
        internal static string CMD_FindReplace {
            get {
                return ResourceManager.GetString("CMD_FindReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Symbol with Name &quot;&lt;NAME&gt;&quot;....
        /// </summary>
        internal static string CMD_FindSymbolwithName {
            get {
                return ResourceManager.GetString("CMD_FindSymbolwithName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Type Referrers....
        /// </summary>
        internal static string CMD_FindTypeReferrers {
            get {
                return ResourceManager.GetString("CMD_FindTypeReferrers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format Document.
        /// </summary>
        internal static string CMD_FormatDocument {
            get {
                return ResourceManager.GetString("CMD_FormatDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format selection.
        /// </summary>
        internal static string CMD_FormatSelection {
            get {
                return ResourceManager.GetString("CMD_FormatSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatting....
        /// </summary>
        internal static string CMD_Formatting {
            get {
                return ResourceManager.GetString("CMD_Formatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to &lt;TYPE&gt;.
        /// </summary>
        internal static string CMD_GoTo {
            get {
                return ResourceManager.GetString("CMD_GoTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to declaration.
        /// </summary>
        internal static string CMD_GoToDeclaration {
            get {
                return ResourceManager.GetString("CMD_GoToDeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Definition.
        /// </summary>
        internal static string CMD_GoToDefinition {
            get {
                return ResourceManager.GetString("CMD_GoToDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to definition
        ///Right click: Peek definition.
        /// </summary>
        internal static string CMD_GoToDefinitionPeek {
            get {
                return ResourceManager.GetString("CMD_GoToDefinitionPeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Member.
        /// </summary>
        internal static string CMD_GotoMember {
            get {
                return ResourceManager.GetString("CMD_GotoMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to project release page.
        /// </summary>
        internal static string CMD_GotoProjectReleasePage {
            get {
                return ResourceManager.GetString("CMD_GotoProjectReleasePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to project web site.
        /// </summary>
        internal static string CMD_GotoProjectWebSite {
            get {
                return ResourceManager.GetString("CMD_GotoProjectWebSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Symbol.
        /// </summary>
        internal static string CMD_GotoSymbol {
            get {
                return ResourceManager.GetString("CMD_GotoSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Type.
        /// </summary>
        internal static string CMD_GotoType {
            get {
                return ResourceManager.GetString("CMD_GotoType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New GUID
        ///Hint: To create a new GUID, type &apos;guid&apos; (without quotes) and select it.
        /// </summary>
        internal static string CMD_GUID {
            get {
                return ResourceManager.GetString("CMD_GUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight.
        /// </summary>
        internal static string CMD_Highlight {
            get {
                return ResourceManager.GetString("CMD_Highlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increment number.
        /// </summary>
        internal static string CMD_IncrementNumber {
            get {
                return ResourceManager.GetString("CMD_IncrementNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indent.
        /// </summary>
        internal static string CMD_Indent {
            get {
                return ResourceManager.GetString("CMD_Indent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert comment.
        /// </summary>
        internal static string CMD_InsertComment {
            get {
                return ResourceManager.GetString("CMD_InsertComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invert operator.
        /// </summary>
        internal static string CMD_InvertOperator {
            get {
                return ResourceManager.GetString("CMD_InvertOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Lines.
        /// </summary>
        internal static string CMD_JoinLines {
            get {
                return ResourceManager.GetString("CMD_JoinLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load....
        /// </summary>
        internal static string CMD_Load {
            get {
                return ResourceManager.GetString("CMD_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lowercase.
        /// </summary>
        internal static string CMD_Lowercase {
            get {
                return ResourceManager.GetString("CMD_Lowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark &lt;NAME&gt;.
        /// </summary>
        internal static string CMD_Mark {
            get {
                return ResourceManager.GetString("CMD_Mark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark symbol....
        /// </summary>
        internal static string CMD_MarkSymbol {
            get {
                return ResourceManager.GetString("CMD_MarkSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open your browser and donate to project Codist.
        /// </summary>
        internal static string CMD_OpenDonatePage {
            get {
                return ResourceManager.GetString("CMD_OpenDonatePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste text from clipboard
        ///Right click: Paste over line
        ///Ctrl click: Paste and select next.
        /// </summary>
        internal static string CMD_Paste {
            get {
                return ResourceManager.GetString("CMD_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin.
        /// </summary>
        internal static string CMD_Pin {
            get {
                return ResourceManager.GetString("CMD_Pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post your opinions in the issues page.
        /// </summary>
        internal static string CMD_PostIssue {
            get {
                return ResourceManager.GetString("CMD_PostIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename symbol.
        /// </summary>
        internal static string CMD_RenameSymbol {
            get {
                return ResourceManager.GetString("CMD_RenameSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reorder parameters.
        /// </summary>
        internal static string CMD_ReorderParameters {
            get {
                return ResourceManager.GetString("CMD_ReorderParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace....
        /// </summary>
        internal static string CMD_Replace {
            get {
                return ResourceManager.GetString("CMD_Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace in Files....
        /// </summary>
        internal static string CMD_ReplaceInFiles {
            get {
                return ResourceManager.GetString("CMD_ReplaceInFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save....
        /// </summary>
        internal static string CMD_Save {
            get {
                return ResourceManager.GetString("CMD_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Declaration.
        /// </summary>
        internal static string CMD_SearchDeclaration {
            get {
                return ResourceManager.GetString("CMD_SearchDeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Titles.
        /// </summary>
        internal static string CMD_SearchTitles {
            get {
                return ResourceManager.GetString("CMD_SearchTitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search with &lt;NAME&gt;....
        /// </summary>
        internal static string CMD_SearchWith {
            get {
                return ResourceManager.GetString("CMD_SearchWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        internal static string CMD_SelectAll {
            get {
                return ResourceManager.GetString("CMD_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Code.
        /// </summary>
        internal static string CMD_SelectCode {
            get {
                return ResourceManager.GetString("CMD_SelectCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select directive region.
        /// </summary>
        internal static string CMD_SelectDirectiveRegion {
            get {
                return ResourceManager.GetString("CMD_SelectDirectiveRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show syntax classification info.
        /// </summary>
        internal static string CMD_ShowSyntaxClassificationInfo {
            get {
                return ResourceManager.GetString("CMD_ShowSyntaxClassificationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surround with....
        /// </summary>
        internal static string CMD_SurroundWith {
            get {
                return ResourceManager.GetString("CMD_SurroundWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag XML Doc with HTML &lt;b&gt;.
        /// </summary>
        internal static string CMD_TagXmlDocB {
            get {
                return ResourceManager.GetString("CMD_TagXmlDocB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag XML Doc with &lt;c&gt;.
        /// </summary>
        internal static string CMD_TagXmlDocC {
            get {
                return ResourceManager.GetString("CMD_TagXmlDocC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag XML Doc with HTML &lt;i&gt;.
        /// </summary>
        internal static string CMD_TagXmlDocI {
            get {
                return ResourceManager.GetString("CMD_TagXmlDocI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag XML Doc with &lt;para&gt;.
        /// </summary>
        internal static string CMD_TagXmlDocPara {
            get {
                return ResourceManager.GetString("CMD_TagXmlDocPara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag XML Doc with &lt;see&gt; or &lt;paramref&gt;.
        /// </summary>
        internal static string CMD_TagXmlDocSee {
            get {
                return ResourceManager.GetString("CMD_TagXmlDocSee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag XML Doc with HTML &lt;u&gt;.
        /// </summary>
        internal static string CMD_TagXmlDocU {
            get {
                return ResourceManager.GetString("CMD_TagXmlDocU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Bookmark.
        /// </summary>
        internal static string CMD_ToggleBookmark {
            get {
                return ResourceManager.GetString("CMD_ToggleBookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Breakpoint.
        /// </summary>
        internal static string CMD_ToggleBreakpoint {
            get {
                return ResourceManager.GetString("CMD_ToggleBreakpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle operator.
        /// </summary>
        internal static string CMD_ToggleOperator {
            get {
                return ResourceManager.GetString("CMD_ToggleOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Parentheses.
        /// </summary>
        internal static string CMD_ToggleParentheses {
            get {
                return ResourceManager.GetString("CMD_ToggleParentheses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle value.
        /// </summary>
        internal static string CMD_ToggleValue {
            get {
                return ResourceManager.GetString("CMD_ToggleValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncomment selection.
        /// </summary>
        internal static string CMD_UncommentSelection {
            get {
                return ResourceManager.GetString("CMD_UncommentSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unindent.
        /// </summary>
        internal static string CMD_Unindent {
            get {
                return ResourceManager.GetString("CMD_Unindent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmark &lt;NAME&gt;.
        /// </summary>
        internal static string CMD_Unmark {
            get {
                return ResourceManager.GetString("CMD_Unmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmark symbol....
        /// </summary>
        internal static string CMD_UnmarkSymbol {
            get {
                return ResourceManager.GetString("CMD_UnmarkSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uppercase.
        /// </summary>
        internal static string CMD_Uppercase {
            get {
                return ResourceManager.GetString("CMD_Uppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all text.
        /// </summary>
        internal static string CMDT_SelectAll {
            get {
                return ResourceManager.GetString("CMDT_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;CommentStyles&quot;: [
        ///    {
        ///      &quot;StyleID&quot;: &quot;Emphasis&quot;,
        ///      &quot;Bold&quot;: true,
        ///      &quot;FontSize&quot;: 7.0
        ///    },
        ///    {
        ///      &quot;StyleID&quot;: &quot;Question&quot;,
        ///      &quot;ForegroundColor&quot;: &quot;#9370DB&quot;
        ///    },
        ///    {
        ///      &quot;StyleID&quot;: &quot;Exclaimation&quot;,
        ///      &quot;ForegroundColor&quot;: &quot;#F9FF0080&quot;
        ///    },
        ///    {
        ///      &quot;StyleID&quot;: &quot;Deletion&quot;,
        ///      &quot;Strikethrough&quot;: true,
        ///      &quot;ForegroundColor&quot;: &quot;#808080&quot;
        ///    },
        ///    {
        ///      &quot;StyleID&quot;: &quot;ToDo&quot;,
        ///      &quot;ForegroundColor&quot;: &quot;#CCCCCC&quot;,
        ///      &quot;BackgroundColor&quot;: &quot;#800000A0&quot;
        ///    },
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;CommentStyles&quot;: [
        ///    {
        ///      &quot;StyleID&quot;: &quot;Emphasis&quot;,
        ///      &quot;Bold&quot;: true,
        ///      &quot;FontSize&quot;: 7.0,
        ///      &quot;ForegroundColor&quot;: &quot;#008000&quot;
        ///    },
        ///    {
        ///      &quot;StyleID&quot;: &quot;Question&quot;,
        ///      &quot;ForegroundColor&quot;: &quot;#9370DB&quot;
        ///    },
        ///    {
        ///      &quot;StyleID&quot;: &quot;Exclaimation&quot;,
        ///      &quot;ForegroundColor&quot;: &quot;#F9FF0080&quot;
        ///    },
        ///    {
        ///      &quot;StyleID&quot;: &quot;Deletion&quot;,
        ///      &quot;Strikethrough&quot;: true,
        ///      &quot;ForegroundColor&quot;: &quot;#808080&quot;
        ///    },
        ///    {
        ///      &quot;StyleID&quot;: &quot;ToDo&quot;,
        ///      &quot;Italic&quot;: false,
        ///      &quot;FontSize&quot;: 3.0,
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string OT_About {
            get {
                return ResourceManager.GetString("OT_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration File.
        /// </summary>
        internal static string OT_ConfigurationFile {
            get {
                return ResourceManager.GetString("OT_ConfigurationFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the following buttons to backup your settings or share the file with others.
        /// </summary>
        internal static string OT_ConfigurationFileTip {
            get {
                return ResourceManager.GetString("OT_ConfigurationFileTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate via PayPal.
        /// </summary>
        internal static string OT_DonateLink {
            get {
                return ResourceManager.GetString("OT_DonateLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended donation value is $19.99. But you can modify the amount to any value if you like.
        /// </summary>
        internal static string OT_DonateLinkTip {
            get {
                return ResourceManager.GetString("OT_DonateLinkTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes will take place on NEWLY OPENED document windows. Currently opened document windows WILL NOT BE AFFECTED.
        /// </summary>
        internal static string OT_FeatureChangesTip {
            get {
                return ResourceManager.GetString("OT_FeatureChangesTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature Controllers.
        /// </summary>
        internal static string OT_FeatureControllers {
            get {
                return ResourceManager.GetString("OT_FeatureControllers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the following checkboxes to control features provided by Codist..
        /// </summary>
        internal static string OT_FeatureControllersTip {
            get {
                return ResourceManager.GetString("OT_FeatureControllersTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string OT_General {
            get {
                return ResourceManager.GetString("OT_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest release:.
        /// </summary>
        internal static string OT_LatestRelease {
            get {
                return ResourceManager.GetString("OT_LatestRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore configurations from a file....
        /// </summary>
        internal static string OT_LoadConfigFileTip {
            get {
                return ResourceManager.GetString("OT_LoadConfigFileTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provides an enhanced navigation bar for C# and Markdown languages.
        /// </summary>
        internal static string OT_NavigationBarTip {
            get {
                return ResourceManager.GetString("OT_NavigationBarTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project web site:.
        /// </summary>
        internal static string OT_ProjectWebSite {
            get {
                return ResourceManager.GetString("OT_ProjectWebSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provides enhancements to Quick Info (code tooltips).
        /// </summary>
        internal static string OT_QuickInfoTip {
            get {
                return ResourceManager.GetString("OT_QuickInfoTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report bugs and suggestions to:.
        /// </summary>
        internal static string OT_ReportBugsAndSuggestions {
            get {
                return ResourceManager.GetString("OT_ReportBugsAndSuggestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup configurations to a file....
        /// </summary>
        internal static string OT_SaveConfigFileTip {
            get {
                return ResourceManager.GetString("OT_SaveConfigFileTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provides additional markers on the scrollbar.
        /// </summary>
        internal static string OT_ScrollbarMarkerTip {
            get {
                return ResourceManager.GetString("OT_ScrollbarMarkerTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provides a dynamic floating toolbar in your code editor.
        /// </summary>
        internal static string OT_SmartBarTip {
            get {
                return ResourceManager.GetString("OT_SmartBarTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support future development of Codist:.
        /// </summary>
        internal static string OT_SupportCodst {
            get {
                return ResourceManager.GetString("OT_SupportCodst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provides advanced syntax highlight and comment taggers.
        /// </summary>
        internal static string OT_SyntaxHighlightTip {
            get {
                return ResourceManager.GetString("OT_SyntaxHighlightTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank You for Using Codist.
        /// </summary>
        internal static string OT_ThankYou {
            get {
                return ResourceManager.GetString("OT_ThankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;CommentStyles&quot;: [
        ///    {
        ///      &quot;StyleID&quot;: &quot;Emphasis&quot;,
        ///      &quot;Bold&quot;: true,
        ///      &quot;FontSize&quot;: 10.0
        ///    },
        ///    {
        ///      &quot;StyleID&quot;: &quot;Deletion&quot;,
        ///      &quot;Strikethrough&quot;: true
        ///    },
        ///    {
        ///      &quot;StyleID&quot;: &quot;Hack&quot;,
        ///      &quot;BackgroundColor&quot;: &quot;#000000&quot;,
        ///      &quot;ScrollBarMarkerStyle&quot;: &quot;Square&quot;
        ///    },
        ///    {
        ///      &quot;StyleID&quot;: &quot;Heading1&quot;,
        ///      &quot;FontSize&quot;: 12.0
        ///    },
        ///    {
        ///      &quot;StyleID&quot;: &quot;Heading2&quot;,
        ///      &quot;FontSize&quot;: 8.0
        ///    },
        ///    {
        ///      &quot;StyleID&quot;: &quot;Heading3&quot;,
        ///      &quot;FontSize&quot;: 4.0
        ///    }
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Simple {
            get {
                return ResourceManager.GetString("Simple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anonymous type: .
        /// </summary>
        internal static string T_AnonymousType {
            get {
                return ResourceManager.GetString("T_AnonymousType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument.
        /// </summary>
        internal static string T_Argument {
            get {
                return ResourceManager.GetString("T_Argument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument &lt;N&gt;.
        /// </summary>
        internal static string T_ArgumentN {
            get {
                return ResourceManager.GetString("T_ArgumentN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument &lt;N&gt; of .
        /// </summary>
        internal static string T_ArgumentNOf {
            get {
                return ResourceManager.GetString("T_ArgumentNOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  of .
        /// </summary>
        internal static string T_ArgumentOf {
            get {
                return ResourceManager.GetString("T_ArgumentOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  as parameter.
        /// </summary>
        internal static string T_AsParameter {
            get {
                return ResourceManager.GetString("T_AsParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly: .
        /// </summary>
        internal static string T_Assembly {
            get {
                return ResourceManager.GetString("T_Assembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute:.
        /// </summary>
        internal static string T_Attribute {
            get {
                return ResourceManager.GetString("T_Attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute of.
        /// </summary>
        internal static string T_AttributeOf {
            get {
                return ResourceManager.GetString("T_AttributeOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base type: .
        /// </summary>
        internal static string T_BaseType {
            get {
                return ResourceManager.GetString("T_BaseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captured variables.
        /// </summary>
        internal static string T_CapturedVariables {
            get {
                return ResourceManager.GetString("T_CapturedVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  characters.
        /// </summary>
        internal static string T_Characters {
            get {
                return ResourceManager.GetString("T_Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chars.
        /// </summary>
        internal static string T_Chars {
            get {
                return ResourceManager.GetString("T_Chars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class: .
        /// </summary>
        internal static string T_Class {
            get {
                return ResourceManager.GetString("T_Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classes.
        /// </summary>
        internal static string T_Classes {
            get {
                return ResourceManager.GetString("T_Classes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        internal static string T_Color {
            get {
                return ResourceManager.GetString("T_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constraint: .
        /// </summary>
        internal static string T_Constraint {
            get {
                return ResourceManager.GetString("T_Constraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Document.
        /// </summary>
        internal static string T_CurrentDocument {
            get {
                return ResourceManager.GetString("T_CurrentDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Project.
        /// </summary>
        internal static string T_CurrentProject {
            get {
                return ResourceManager.GetString("T_CurrentProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declared variable: .
        /// </summary>
        internal static string T_DeclaredVariable {
            get {
                return ResourceManager.GetString("T_DeclaredVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to defined in .
        /// </summary>
        internal static string T_DefinedIn {
            get {
                return ResourceManager.GetString("T_DefinedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defined in: .
        /// </summary>
        internal static string T_DefinedInType {
            get {
                return ResourceManager.GetString("T_DefinedInType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delegate; attach or detach event.
        /// </summary>
        internal static string T_DelegateEvent {
            get {
                return ResourceManager.GetString("T_DelegateEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delegates.
        /// </summary>
        internal static string T_Delegates {
            get {
                return ResourceManager.GetString("T_Delegates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delegate signature.
        /// </summary>
        internal static string T_DelegateSignature {
            get {
                return ResourceManager.GetString("T_DelegateSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  derived classes.
        /// </summary>
        internal static string T_DerivedClasses {
            get {
                return ResourceManager.GetString("T_DerivedClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation from .
        /// </summary>
        internal static string T_DocumentationFrom {
            get {
                return ResourceManager.GetString("T_DocumentationFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of region .
        /// </summary>
        internal static string T_EndOfRegion {
            get {
                return ResourceManager.GetString("T_EndOfRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All flags: .
        /// </summary>
        internal static string T_EnumAllFlags {
            get {
                return ResourceManager.GetString("T_EnumAllFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumerations.
        /// </summary>
        internal static string T_Enumerations {
            get {
                return ResourceManager.GetString("T_Enumerations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field count:.
        /// </summary>
        internal static string T_EnumFieldCount {
            get {
                return ResourceManager.GetString("T_EnumFieldCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max: .
        /// </summary>
        internal static string T_EnumMax {
            get {
                return ResourceManager.GetString("T_EnumMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min: .
        /// </summary>
        internal static string T_EnumMin {
            get {
                return ResourceManager.GetString("T_EnumMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enum underlying type: .
        /// </summary>
        internal static string T_EnumUnderlyingType {
            get {
                return ResourceManager.GetString("T_EnumUnderlyingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        internal static string T_Events {
            get {
                return ResourceManager.GetString("T_Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event signature .
        /// </summary>
        internal static string T_EventSignature {
            get {
                return ResourceManager.GetString("T_EventSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example.
        /// </summary>
        internal static string T_Example {
            get {
                return ResourceManager.GetString("T_Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception.
        /// </summary>
        internal static string T_Exception {
            get {
                return ResourceManager.GetString("T_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explicit implements:.
        /// </summary>
        internal static string T_ExplicitImplements {
            get {
                return ResourceManager.GetString("T_ExplicitImplements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  extensions.
        /// </summary>
        internal static string T_Extensions {
            get {
                return ResourceManager.GetString("T_Extensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields and properties.
        /// </summary>
        internal static string T_FieldsProperties {
            get {
                return ResourceManager.GetString("T_FieldsProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hash code.
        /// </summary>
        internal static string T_HashCode {
            get {
                return ResourceManager.GetString("T_HashCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  implementations: .
        /// </summary>
        internal static string T_Implementations {
            get {
                return ResourceManager.GetString("T_Implementations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Implements:.
        /// </summary>
        internal static string T_Implements {
            get {
                return ResourceManager.GetString("T_Implements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (inherited).
        /// </summary>
        internal static string T_Inherited {
            get {
                return ResourceManager.GetString("T_Inherited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface:.
        /// </summary>
        internal static string T_Interface {
            get {
                return ResourceManager.GetString("T_Interface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interfaces.
        /// </summary>
        internal static string T_Interfaces {
            get {
                return ResourceManager.GetString("T_Interfaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal and private types.
        /// </summary>
        internal static string T_InternalPrivateTypes {
            get {
                return ResourceManager.GetString("T_InternalPrivateTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lambda expression.
        /// </summary>
        internal static string T_LambdaExpression {
            get {
                return ResourceManager.GetString("T_LambdaExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line of code: .
        /// </summary>
        internal static string T_LineOfCode {
            get {
                return ResourceManager.GetString("T_LineOfCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  lines.
        /// </summary>
        internal static string T_Lines {
            get {
                return ResourceManager.GetString("T_Lines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locations: .
        /// </summary>
        internal static string T_Locations {
            get {
                return ResourceManager.GetString("T_Locations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maybe....
        /// </summary>
        internal static string T_Maybe {
            get {
                return ResourceManager.GetString("T_Maybe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maybe.
        /// </summary>
        internal static string T_MaybeArgument {
            get {
                return ResourceManager.GetString("T_MaybeArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  argument of.
        /// </summary>
        internal static string T_MaybeArgumentOf {
            get {
                return ResourceManager.GetString("T_MaybeArgumentOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member:.
        /// </summary>
        internal static string T_Member {
            get {
                return ResourceManager.GetString("T_Member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  members: {count} ({inherited} inherited).
        /// </summary>
        internal static string T_Members {
            get {
                return ResourceManager.GetString("T_Members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member type: .
        /// </summary>
        internal static string T_MemberType {
            get {
                return ResourceManager.GetString("T_MemberType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method overload:.
        /// </summary>
        internal static string T_MethodOverload {
            get {
                return ResourceManager.GetString("T_MethodOverload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Methods.
        /// </summary>
        internal static string T_Methods {
            get {
                return ResourceManager.GetString("T_Methods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  name alike.
        /// </summary>
        internal static string T_NameAlike {
            get {
                return ResourceManager.GetString("T_NameAlike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace: .
        /// </summary>
        internal static string T_Namespace {
            get {
                return ResourceManager.GetString("T_Namespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespaces.
        /// </summary>
        internal static string T_Namespaces {
            get {
                return ResourceManager.GetString("T_Namespaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation Bar.
        /// </summary>
        internal static string T_NavigationBar {
            get {
                return ResourceManager.GetString("T_NavigationBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  overrides: .
        /// </summary>
        internal static string T_Overrides {
            get {
                return ResourceManager.GetString("T_Overrides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  producers.
        /// </summary>
        internal static string T_Producers {
            get {
                return ResourceManager.GetString("T_Producers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public and protected types.
        /// </summary>
        internal static string T_PublicProtectedTypes {
            get {
                return ResourceManager.GetString("T_PublicProtectedTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read variable: .
        /// </summary>
        internal static string T_ReadVariable {
            get {
                return ResourceManager.GetString("T_ReadVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  referenced symbols: .
        /// </summary>
        internal static string T_ReferencedSymbols {
            get {
                return ResourceManager.GetString("T_ReferencedSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  referrers.
        /// </summary>
        internal static string T_Referrers {
            get {
                return ResourceManager.GetString("T_Referrers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        internal static string T_Remarks {
            get {
                return ResourceManager.GetString("T_Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result Filter.
        /// </summary>
        internal static string T_ResultFilter {
            get {
                return ResourceManager.GetString("T_ResultFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter items in this menu.
        ///Use space to separate keywords..
        /// </summary>
        internal static string T_ResultFilterTip {
            get {
                return ResourceManager.GetString("T_ResultFilterTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return .
        /// </summary>
        internal static string T_Return {
            get {
                return ResourceManager.GetString("T_Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return anonymous function for .
        /// </summary>
        internal static string T_ReturnAnonymousFunction {
            get {
                return ResourceManager.GetString("T_ReturnAnonymousFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  for .
        /// </summary>
        internal static string T_ReturnFor {
            get {
                return ResourceManager.GetString("T_ReturnFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns.
        /// </summary>
        internal static string T_Returns {
            get {
                return ResourceManager.GetString("T_Returns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrollbar Markers.
        /// </summary>
        internal static string T_ScrollbarMarkers {
            get {
                return ResourceManager.GetString("T_ScrollbarMarkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See also.
        /// </summary>
        internal static string T_SeeAlso {
            get {
                return ResourceManager.GetString("T_SeeAlso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected character:.
        /// </summary>
        internal static string T_SelectedCharacter {
            get {
                return ResourceManager.GetString("T_SelectedCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection: .
        /// </summary>
        internal static string T_Selection {
            get {
                return ResourceManager.GetString("T_Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature: .
        /// </summary>
        internal static string T_Signature {
            get {
                return ResourceManager.GetString("T_Signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  signature match.
        /// </summary>
        internal static string T_SignatureMatch {
            get {
                return ResourceManager.GetString("T_SignatureMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart Bar.
        /// </summary>
        internal static string T_SmartBar {
            get {
                return ResourceManager.GetString("T_SmartBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source file: .
        /// </summary>
        internal static string T_SourceFile {
            get {
                return ResourceManager.GetString("T_SourceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  source locations: .
        /// </summary>
        internal static string T_SourceLocations {
            get {
                return ResourceManager.GetString("T_SourceLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  spans.
        /// </summary>
        internal static string T_Spans {
            get {
                return ResourceManager.GetString("T_Spans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structures.
        /// </summary>
        internal static string T_Structures {
            get {
                return ResourceManager.GetString("T_Structures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super Quick Info.
        /// </summary>
        internal static string T_SuperQuickInfo {
            get {
                return ResourceManager.GetString("T_SuperQuickInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol unavailable in:.
        /// </summary>
        internal static string T_SymbolUnavailableIn {
            get {
                return ResourceManager.GetString("T_SymbolUnavailableIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax Highlight.
        /// </summary>
        internal static string T_SyntaxHighlight {
            get {
                return ResourceManager.GetString("T_SyntaxHighlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text.
        /// </summary>
        internal static string T_Text {
            get {
                return ResourceManager.GetString("T_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        internal static string T_Type {
            get {
                return ResourceManager.GetString("T_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type argument:.
        /// </summary>
        internal static string T_TypeArgument {
            get {
                return ResourceManager.GetString("T_TypeArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type conversion.
        /// </summary>
        internal static string T_TypeConversion {
            get {
                return ResourceManager.GetString("T_TypeConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type reference or argument.
        /// </summary>
        internal static string T_TypeReferenceOrArgument {
            get {
                return ResourceManager.GetString("T_TypeReferenceOrArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types and delegates.
        /// </summary>
        internal static string T_TypesDelegates {
            get {
                return ResourceManager.GetString("T_TypesDelegates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write.
        /// </summary>
        internal static string T_Write {
            get {
                return ResourceManager.GetString("T_Write", resourceCulture);
            }
        }
    }
}
